//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.PurchaseOrders = new HashSet<PurchaseOrders>();
            this.Users = new HashSet<Users>();
            this.WorkLogs = new HashSet<WorkLogs>();
        }
    
        public int EmployeeID { get; set; }
        public string PhoneNumber { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string MiddleName { get; set; }
        public int PositionID { get; set; }
        public int DepartmentID { get; set; }
        public int QualificationID { get; set; }
        public int SalaryTypeID { get; set; }
        public int EmployeeStatusID { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual EmployeeStatuses EmployeeStatuses { get; set; }
        public virtual Positions Positions { get; set; }
        public virtual Qualifications Qualifications { get; set; }
        public virtual SalaryTypes SalaryTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrders> PurchaseOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkLogs> WorkLogs { get; set; }
    }
}
