//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentUsageLogs
    {
        public int EquipmentUsageLogID { get; set; }
        public int EquipmentID { get; set; }
        public int ProductionStageID { get; set; }
        public decimal UsageHours { get; set; }
        public System.DateTime UsageDate { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual ProductionStages ProductionStages { get; set; }
    }
}
