//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.EquipmentUsageLogs = new HashSet<EquipmentUsageLogs>();
        }
    
        public int EquipmentID { get; set; }
        public string InventoryNumber { get; set; }
        public int ModelID { get; set; }
        public int EquipmentTypeID { get; set; }
        public System.DateTime CommissionDate { get; set; }
        public int EquipmentStatusID { get; set; }
        public string MaintenanceSchedule { get; set; }
    
        public virtual EquipmentTypes EquipmentTypes { get; set; }
        public virtual EquipmentStatuses EquipmentStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentUsageLogs> EquipmentUsageLogs { get; set; }
        public virtual Models Models { get; set; }
    }
}
