//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.BillOfMaterials = new HashSet<BillOfMaterials>();
            this.StockBalances = new HashSet<StockBalances>();
        }
    
        public int MaterialID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int MaterialTypeID { get; set; }
        public int UnitID { get; set; }
        public decimal MinStock { get; set; }
        public decimal MarketPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillOfMaterials> BillOfMaterials { get; set; }
        public virtual MaterialTypes MaterialTypes { get; set; }
        public virtual Units Units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockBalances> StockBalances { get; set; }
    }
}
