//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LogisticsEntities : DbContext
    {
        public LogisticsEntities()
            : base("name=LogisticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BillOfMaterials> BillOfMaterials { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<EmployeeStatuses> EmployeeStatuses { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<EquipmentStatuses> EquipmentStatuses { get; set; }
        public virtual DbSet<EquipmentTypes> EquipmentTypes { get; set; }
        public virtual DbSet<EquipmentUsageLogs> EquipmentUsageLogs { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<MaterialTypes> MaterialTypes { get; set; }
        public virtual DbSet<Models> Models { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<ProductCategories> ProductCategories { get; set; }
        public virtual DbSet<ProductionOrders> ProductionOrders { get; set; }
        public virtual DbSet<ProductionOrderStatuses> ProductionOrderStatuses { get; set; }
        public virtual DbSet<ProductionStages> ProductionStages { get; set; }
        public virtual DbSet<ProductionStageStatuses> ProductionStageStatuses { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductStatuses> ProductStatuses { get; set; }
        public virtual DbSet<PurchaseOrders> PurchaseOrders { get; set; }
        public virtual DbSet<PurchaseReceipts> PurchaseReceipts { get; set; }
        public virtual DbSet<PurchaseStatuses> PurchaseStatuses { get; set; }
        public virtual DbSet<Qualifications> Qualifications { get; set; }
        public virtual DbSet<QualityDefects> QualityDefects { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SalaryTypes> SalaryTypes { get; set; }
        public virtual DbSet<Stages> Stages { get; set; }
        public virtual DbSet<StockBalances> StockBalances { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TechOperations> TechOperations { get; set; }
        public virtual DbSet<TechRoutes> TechRoutes { get; set; }
        public virtual DbSet<Units> Units { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Warehouses> Warehouses { get; set; }
        public virtual DbSet<WarehouseTypes> WarehouseTypes { get; set; }
        public virtual DbSet<WorkLogs> WorkLogs { get; set; }
    }
}
