//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionStages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionStages()
        {
            this.EquipmentUsageLogs = new HashSet<EquipmentUsageLogs>();
            this.QualityDefects = new HashSet<QualityDefects>();
            this.WorkLogs = new HashSet<WorkLogs>();
        }
    
        public int ProductionStageID { get; set; }
        public int ProductionOrderID { get; set; }
        public int StageID { get; set; }
        public int ProductionStageStatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentUsageLogs> EquipmentUsageLogs { get; set; }
        public virtual ProductionOrders ProductionOrders { get; set; }
        public virtual ProductionStageStatuses ProductionStageStatuses { get; set; }
        public virtual Stages Stages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityDefects> QualityDefects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkLogs> WorkLogs { get; set; }
    }
}
