//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionOrders()
        {
            this.ProductionStages = new HashSet<ProductionStages>();
        }
    
        public int ProductionOrderID { get; set; }
        public int ClientID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public int Priority { get; set; }
        public System.DateTime Deadline { get; set; }
        public int ProductionOrderStatusID { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionStages> ProductionStages { get; set; }
        public virtual Products Products { get; set; }
        public virtual ProductionOrderStatuses ProductionOrderStatuses { get; set; }
    }
}
