//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseReceipts
    {
        public int PurchaseReceiptID { get; set; }
        public int PurchaseOrderID { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public decimal AcceptedQuantity { get; set; }
        public decimal DefectQuantity { get; set; }
    
        public virtual PurchaseOrders PurchaseOrders { get; set; }
    }
}
