//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityDefects
    {
        public int QualityDefectID { get; set; }
        public int ProductionStageID { get; set; }
        public string Description { get; set; }
        public System.DateTime DefectDate { get; set; }
    
        public virtual ProductionStages ProductionStages { get; set; }
    }
}
