//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockBalances
    {
        public int StockBalanceID { get; set; }
        public int WarehouseID { get; set; }
        public int MaterialID { get; set; }
        public decimal Quantity { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
