//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechOperations
    {
        public int TechOperationID { get; set; }
        public int TechRouteID { get; set; }
        public string Name { get; set; }
        public int SequenceNumber { get; set; }
        public int DurationMinutes { get; set; }
    
        public virtual TechRoutes TechRoutes { get; set; }
    }
}
