//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkLogs
    {
        public int WorkLogID { get; set; }
        public int EmployeeID { get; set; }
        public int ProductionStageID { get; set; }
        public decimal HoursWorked { get; set; }
        public System.DateTime WorkDate { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual ProductionStages ProductionStages { get; set; }
    }
}
